spring:
  redis:
    host: localhost #redis服务器地址
    port: 6379      #redis服务器连接端口
    database: 1     #redis数据库索引
    lettuce:        #springboot 2.0提供的默认的redis客户端
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    #    jedis:          #springboot 1.0提供的默认的redis客户端
    #      pool:
    #        max-active: 8 #连接池最大连接数，默认为8
    #        max-wait: -1  #连接池最大1阻塞等待时间，默认为-1，表示没有限制
    #        max-idle: 8   #连接池中的最大空闲连接，默认为8
    #        min-idle: 0   #连接池中的最小空闲连接，默认为0
    timeout: 500      #设置最大超时时间

